### ISSUE TITLE
TAP

### ISSUE THREAD

**Issue by pireybr** [EricZimmerman/Voron24#1]
Congratulations Eric, the code is awesome...

what I need to change to use it with tap?

**Comment by EricZimmerman** [comment]
what code specifically? i use tap now?

**Comment by pireybr** [comment]
Print start, there is some dock probe codes there

**Comment by EricZimmerman** [comment]
I'll have to look. As those might be old remnants of my pre-tap configs.

I'll go ahead and make sure that my repo is updated with my current stuff
here in a bit, but once I do that it should be ready for tap.

**Comment by EricZimmerman** [comment]
its current now. have a look. will close this for now
